{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8df4b7b-2f32-4b47-b1b2-6887969f9ca3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# =============================================\n",
    "# 🚀 TOP 10 BUY IBEX 35 con Técnicos + Fundamentales + Noticias + Riesgo + Cartera Óptima\n",
    "# Versión Streamlit - Funcional y lista para pegar en .py\n",
    "# =============================================\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import yfinance as yf\n",
    "import ta\n",
    "import time\n",
    "import math\n",
    "import feedparser\n",
    "import urllib.parse\n",
    "import warnings\n",
    "import numpy as np\n",
    "\n",
    "from pypfopt.efficient_frontier import EfficientFrontier\n",
    "from pypfopt import risk_models, expected_returns\n",
    "from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer\n",
    "\n",
    "warnings.simplefilter(action='ignore', category=FutureWarning)\n",
    "\n",
    "# -------------------------\n",
    "# Configuración Streamlit\n",
    "# -------------------------\n",
    "st.set_page_config(page_title=\"Análisis IBEX 35\", layout=\"wide\")\n",
    "st.title(\"📊 Análisis de Empresas - IBEX 35\")\n",
    "st.sidebar.header(\"Opciones de análisis\")\n",
    "\n",
    "# -------------------------\n",
    "# Parámetros configurables\n",
    "# -------------------------\n",
    "PERIOD = st.sidebar.selectbox(\"Periodo histórico\", [\"1mo\",\"3mo\",\"6mo\",\"1y\"], index=1)\n",
    "INTERVAL = st.sidebar.selectbox(\"Intervalo\", [\"1d\",\"1wk\",\"1mo\"], index=0)\n",
    "TECH_THRESHOLD = 2\n",
    "FUND_THRESHOLD = 2\n",
    "NEWS_THRESHOLD = 0.05\n",
    "NEWS_PER_SOURCE = 5\n",
    "\n",
    "PE_MAX = 35.0\n",
    "DTE_MAX = 1.5\n",
    "ROE_MIN = 0.05\n",
    "PM_MIN = 0.03\n",
    "RSI_MAX_FOR_BUY = 50.0\n",
    "\n",
    "# -------------------------\n",
    "# Empresas IBEX 35\n",
    "# -------------------------\n",
    "EMPRESAS = {\n",
    "    \"ANA.MC\": \"Acciona\", \"ACX.MC\": \"Acerinox\", \"ACS.MC\": \"ACS\",\n",
    "    \"AENA.MC\": \"Aena\", \"ALM.MC\": \"Almirall\", \"AMS.MC\": \"Amadeus\",\n",
    "    \"SAB.MC\": \"Banco Sabadell\", \"SAN.MC\": \"Banco Santander\", \"BBVA.MC\": \"BBVA\",\n",
    "    \"CABK.MC\": \"CaixaBank\", \"CLNX.MC\": \"Cellnex\", \"CIE.MC\": \"CIE Automotive\",\n",
    "    \"COL.MC\": \"Colonial\", \"ENG.MC\": \"Enagás\", \"ELE.MC\": \"Endesa\",\n",
    "    \"FER.MC\": \"Ferrovial\", \"GRF.MC\": \"Grifols\", \"IBE.MC\": \"Iberdrola\",\n",
    "    \"ITX.MC\": \"Inditex\", \"IDR.MC\": \"Indra\", \"MAP.MC\": \"Mapfre\",\n",
    "    \"MEL.MC\": \"Meliá Hotels\", \"NTGY.MC\": \"Naturgy\", \"PHM.MC\": \"PharmaMar\",\n",
    "    \"RED.MC\": \"Redeia\", \"REP.MC\": \"Repsol\", \"ROVI.MC\": \"Rovi\",\n",
    "    \"SLR.MC\": \"Solaria\", \"TEF.MC\": \"Telefónica\", \"UNI.MC\": \"Unicaja Banco\",\n",
    "    \"VIS.MC\": \"Viscofan\", \"LOG.MC\": \"Logista\"\n",
    "}\n",
    "\n",
    "# -------------------------\n",
    "# Inicializar VADER\n",
    "# -------------------------\n",
    "analyzer = SentimentIntensityAnalyzer()\n",
    "\n",
    "# -------------------------\n",
    "# Funciones auxiliares\n",
    "# -------------------------\n",
    "def obtener_feed_google_news(query):\n",
    "    query_enc = urllib.parse.quote(query)\n",
    "    url_es = f\"https://news.google.com/rss/search?q={query_enc}&hl=es&gl=ES&ceid=ES:ES\"\n",
    "    url_en = f\"https://news.google.com/rss/search?q={query_enc}&hl=en&gl=US&ceid=US:en\"\n",
    "    return [url_es, url_en]\n",
    "\n",
    "def evaluar_noticias(ticker, n=NEWS_PER_SOURCE):\n",
    "    nombre = EMPRESAS.get(ticker)\n",
    "    if not nombre: return 0\n",
    "    score_total = 0\n",
    "    feeds = obtener_feed_google_news(nombre)\n",
    "    for feed_url in feeds:\n",
    "        feed = feedparser.parse(feed_url)\n",
    "        for entry in feed.entries[:n]:\n",
    "            vs = analyzer.polarity_scores(entry.title)\n",
    "            score_total += vs['compound']\n",
    "    total_items = len(feeds)*n\n",
    "    return score_total / total_items if total_items>0 else 0\n",
    "\n",
    "def es_bullish_engulfing(df):\n",
    "    if len(df)<2: return False\n",
    "    prev, last = df.iloc[-2], df.iloc[-1]\n",
    "    return prev['Close']<prev['Open'] and last['Close']>last['Open'] and last['Close']>prev['Open'] and last['Open']<prev['Close']\n",
    "\n",
    "def evaluar_fundamentales(ticker):\n",
    "    try:\n",
    "        info = yf.Ticker(ticker).info\n",
    "    except: return {\"score\":0,\"details\":{},\"raw\":{}}\n",
    "    score = 0\n",
    "    details = {}\n",
    "    pe = info.get('trailingPE') or info.get('forwardPE')\n",
    "    if pe and 0<pe<PE_MAX: score+=1; details['PE_ok']=True\n",
    "    else: details['PE_ok']=False\n",
    "    dte = info.get('debtToEquity') or info.get('totalDebt')\n",
    "    try: dte_val = float(dte) if dte else None\n",
    "    except: dte_val=None\n",
    "    if dte_val is not None and dte_val<DTE_MAX: score+=1; details['D/E_ok']=True\n",
    "    else: details['D/E_ok']=False\n",
    "    roe = info.get('returnOnEquity') or info.get('returnOnInvestment')\n",
    "    try: roe_val=float(roe) if roe else None\n",
    "    except: roe_val=None\n",
    "    if roe_val and roe_val>ROE_MIN: score+=1; details['ROE_ok']=True\n",
    "    else: details['ROE_ok']=False\n",
    "    pm = info.get('profitMargins')\n",
    "    try: pm_val=float(pm) if pm else None\n",
    "    except: pm_val=None\n",
    "    if pm_val and pm_val>PM_MIN: score+=1; details['PM_ok']=True\n",
    "    else: details['PM_ok']=False\n",
    "    return {\"score\":score,\"details\":details,\"raw\":info}\n",
    "\n",
    "def evaluar_tecnica(ticker):\n",
    "    try:\n",
    "        df = yf.download(ticker, period=PERIOD, interval=INTERVAL, progress=False, auto_adjust=True)\n",
    "        if df.empty: return None\n",
    "        df = df.dropna(subset=['Open','Close'])\n",
    "        if len(df)<30: return None\n",
    "        close = df['Close'].astype(float)\n",
    "        ema20 = close.ewm(span=20, adjust=False).mean()\n",
    "        ema50 = close.ewm(span=50, adjust=False).mean()\n",
    "        rsi = ta.momentum.RSIIndicator(close, window=14).rsi()\n",
    "        macd_obj = ta.trend.MACD(close)\n",
    "        macd, macd_signal = macd_obj.macd(), macd_obj.macd_signal()\n",
    "        bull = es_bullish_engulfing(df)\n",
    "        conditions = [rsi.iloc[-1]<RSI_MAX_FOR_BUY, ema20.iloc[-1]>=ema50.iloc[-1], macd.iloc[-1]>macd_signal.iloc[-1], bull]\n",
    "        tech_score = sum(bool(c) for c in conditions)\n",
    "        return {'RSI':rsi.iloc[-1],'EMA20':ema20.iloc[-1],'EMA50':ema50.iloc[-1],\n",
    "                'MACD':macd.iloc[-1],'MACD_signal':macd_signal.iloc[-1],\n",
    "                'Bullish':bull,'tech_score':tech_score}\n",
    "    except: return None\n",
    "\n",
    "def calcular_metricas(ticker):\n",
    "    try:\n",
    "        data = yf.download(ticker, period=\"1y\", interval=\"1d\")['Close'].dropna()\n",
    "        rets = data.pct_change().dropna()\n",
    "        sharpe = (rets.mean()/rets.std()) * np.sqrt(252)\n",
    "        max_dd = ((data / data.cummax())-1).min()\n",
    "        return round(sharpe,2), round(max_dd,2)\n",
    "    except: return None, None\n",
    "\n",
    "def optimizar_cartera(tickers):\n",
    "    try:\n",
    "        precios = yf.download(tickers, period=\"1y\", interval=\"1d\")['Close'].dropna(axis=1)\n",
    "        mu = expected_returns.mean_historical_return(precios)\n",
    "        S = risk_models.sample_cov(precios)\n",
    "        ef = EfficientFrontier(mu,S)\n",
    "        pesos = ef.max_sharpe()\n",
    "        return ef.clean_weights()\n",
    "    except: return {}\n",
    "\n",
    "# -------------------------\n",
    "# Main Streamlit\n",
    "# -------------------------\n",
    "st.header(\"📈 Resultados por Empresa\")\n",
    "\n",
    "resultados=[]\n",
    "for t in EMPRESAS.keys():\n",
    "    tech = evaluar_tecnica(t)\n",
    "    fund = evaluar_fundamentales(t)\n",
    "    news = evaluar_noticias(t)\n",
    "    tech_score = tech['tech_score'] if tech else 0\n",
    "    fund_score = fund['score'] if fund else 0\n",
    "    etiqueta = None\n",
    "    if tech_score>=TECH_THRESHOLD and fund_score>=FUND_THRESHOLD and news>=NEWS_THRESHOLD:\n",
    "        etiqueta=\"STRONG BUY\"\n",
    "    elif tech_score>=TECH_THRESHOLD or fund_score>=FUND_THRESHOLD or news>0:\n",
    "        etiqueta=\"BUY\"\n",
    "    if etiqueta:\n",
    "        sharpe, dd = calcular_metricas(t)\n",
    "        resultados.append({\n",
    "            'Ticker': t,\n",
    "            'Empresa': EMPRESAS[t],\n",
    "            'Etiqueta': etiqueta,\n",
    "            'TechScore': tech_score,\n",
    "            'FundScore': fund_score,\n",
    "            'NewsScore': round(news,3),\n",
    "            'RSI': round(tech['RSI'],2) if tech else math.nan,\n",
    "            'Sharpe': sharpe,\n",
    "            'Drawdown': dd\n",
    "        })\n",
    "\n",
    "if resultados:\n",
    "    df = pd.DataFrame(resultados)\n",
    "    df = df.sort_values(by=['Etiqueta','NewsScore','RSI'], ascending=[True,False,True]).head(10)\n",
    "    st.dataframe(df, use_container_width=True)\n",
    "    \n",
    "    # Descarga CSV\n",
    "    csv = df.to_csv(index=False).encode('utf-8')\n",
    "    st.download_button(\"📥 Descargar CSV\", data=csv, file_name=\"top_ibex.csv\", mime=\"text/csv\")\n",
    "    \n",
    "    # Gráficos\n",
    "    st.header(\"📊 Gráficos de Scores\")\n",
    "    for _, row in df.iterrows():\n",
    "        st.subheader(f\"{row['Empresa']} ({row['Etiqueta']})\")\n",
    "        st.bar_chart(pd.DataFrame({\n",
    "            'TechScore':[row['TechScore']],\n",
    "            'FundScore':[row['FundScore']],\n",
    "            'NewsScore':[row['NewsScore']]\n",
    "        }))\n",
    "    \n",
    "    # Optimización cartera\n",
    "    st.header(\"💼 Cartera Óptima (Max Sharpe)\")\n",
    "    pesos = optimizar_cartera(df['Ticker'].tolist())\n",
    "    for t, w in pesos.items():\n",
    "        if w>0:\n",
    "            st.write(f\"{t}: {round(w*100,2)}%\")\n",
    "else:\n",
    "    st.warning(\"No se encontraron STRONG BUY o BUY según los criterios.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
